# Generated by Django 6.0.8 on 2026-09-17 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('knowledge_type', models.CharField(choices=[('note', 'Note'), ('document', 'Document'), ('article', 'Article'), ('documentation', 'Documentation'), ('idea', 'Idea'), ('project', 'Project'), ('learning', 'Learning'), ('reference', 'Reference'), ('other', 'Other')], default='note', max_length=30)),
                ('source_url', models.URLField(blank=True)),
                ('source_name', models.CharField(blank=True, max_length=255)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('shared', 'Shared')], default='private', max_length=20)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='knowledge/files/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word'), ('excel', 'Excel'), ('powerpoint', 'PowerPoint'), ('markdown', 'Markdown'), ('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('code', 'Code'), ('other', 'Other')], default='other', max_length=30)),
                ('mime_type', models.CharField(blank=True, max_length=150)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('knowledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='knowledge.knowledgeitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='knowledgeitem',
            index=models.Index(fields=['user', 'knowledge_type'], name='knowledge_k_user_id_29f27d_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeitem',
            index=models.Index(fields=['user', 'is_archived'], name='knowledge_k_user_id_f8dc2b_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeitem',
            index=models.Index(fields=['user', 'created_at'], name='knowledge_k_user_id_4485df_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgefile',
            index=models.Index(fields=['knowledge', 'file_type'], name='knowledge_k_knowled_c6a337_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgefile',
            index=models.Index(fields=['knowledge', 'created_at'], name='knowledge_k_knowled_522aaa_idx'),
        ),
    ]
