# Generated by Django 6.0.8 on 2026-09-12 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('knowledge_type', models.CharField(choices=[('note', 'Note'), ('document', 'Document'), ('article', 'Article'), ('documentation', 'Documentation'), ('idea', 'Idea'), ('project', 'Project'), ('learning', 'Learning'), ('reference', 'Reference'), ('other', 'Other')], default='note', max_length=30)),
                ('source_url', models.URLField(blank=True)),
                ('source_name', models.CharField(blank=True, max_length=255)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('shared', 'Shared')], default='private', max_length=20)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'knowledge_type'], name='knowledge_k_user_id_29f27d_idx'), models.Index(fields=['user', 'is_archived'], name='knowledge_k_user_id_f8dc2b_idx'), models.Index(fields=['user', 'created_at'], name='knowledge_k_user_id_4485df_idx')],
            },
        ),
    ]
