# Generated by Django 6.0.8 on 2026-09-17 01:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='knowledgefile',
            new_name='knowledge_file_type_idx',
            old_name='knowledge_k_knowled_c6a337_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgefile',
            new_name='knowledge_file_created_idx',
            old_name='knowledge_k_knowled_522aaa_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgeitem',
            new_name='knowledge_user_type_idx',
            old_name='knowledge_k_user_id_29f27d_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgeitem',
            new_name='knowledge_user_archived_idx',
            old_name='knowledge_k_user_id_f8dc2b_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgeitem',
            new_name='knowledge_user_created_idx',
            old_name='knowledge_k_user_id_4485df_idx',
        ),
        migrations.AddIndex(
            model_name='knowledgeitem',
            index=models.Index(fields=['user', 'updated_at'], name='knowledge_user_updated_idx'),
        ),
    ]
