# Generated by Django 6.0.8 on 2026-09-12 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='knowledge/files/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word'), ('excel', 'Excel'), ('powerpoint', 'PowerPoint'), ('markdown', 'Markdown'), ('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('code', 'Code'), ('other', 'Other')], default='other', max_length=30)),
                ('mime_type', models.CharField(blank=True, max_length=150)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('knowledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='knowledge.knowledgeitem')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['knowledge', 'file_type'], name='knowledge_k_knowled_c6a337_idx'), models.Index(fields=['knowledge', 'created_at'], name='knowledge_k_knowled_522aaa_idx')],
            },
        ),
    ]
