# Generated by Django 6.0.8 on 2026-09-16 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_knowledgefile'),
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgeitem',
            name='learning_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_items', to='learning.learningtopic'),
        ),
    ]
