# Generated by Django 6.0.8 on 2026-10-01 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_social_profile_recommendation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='socialprofile',
            new_name='social_soci_discove_ecbbb4_idx',
            old_name='social_profile_disc_idx',
        ),
        migrations.RenameIndex(
            model_name='socialrecommendation',
            new_name='social_soci_user_id_d717ae_idx',
            old_name='social_rec_user_score_idx',
        ),
    ]
