from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True
    dependencies = [("users_accounts", "0001_initial"), ("learning", "0002_alter_knowledgeapplication_knowledge_item")]
    operations = [
        migrations.CreateModel(name="JobSource", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("name", models.CharField(max_length=150)), ("source_type", models.CharField(choices=[("api","Official API"),("rss","RSS/Public Feed"),("manual","Manual")], default="manual", max_length=20)),
            ("base_url", models.URLField(blank=True)), ("feed_url", models.URLField(blank=True)), ("enabled", models.BooleanField(default=True)), ("config", models.JSONField(blank=True, default=dict)), ("last_synced_at", models.DateTimeField(blank=True, null=True)), ("last_sync_status", models.CharField(default="never", max_length=20)), ("last_sync_error", models.TextField(blank=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)),
            ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="job_sources", to=settings.AUTH_USER_MODEL)),
        ], options={"ordering":["name"], "constraints":[models.UniqueConstraint(fields=["user","name"], name="jobs_source_user_name_unique")]}),
        migrations.CreateModel(name="JobOpportunity", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("external_id", models.CharField(blank=True, max_length=255)), ("title", models.CharField(max_length=255)), ("company", models.CharField(blank=True, max_length=255)), ("description", models.TextField(blank=True)), ("url", models.URLField(blank=True)), ("location", models.CharField(blank=True, max_length=255)), ("is_remote", models.BooleanField(default=False)), ("job_type", models.CharField(choices=[("full_time","Full time"),("part_time","Part time"),("contract","Contract"),("freelance","Freelance"),("internship","Internship"),("project","Project")], default="full_time", max_length=30)), ("salary_min", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)), ("salary_max", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)), ("currency", models.CharField(default="USD", max_length=10)), ("metadata", models.JSONField(blank=True, default=dict)), ("published_at", models.DateTimeField(blank=True, null=True)), ("discovered_at", models.DateTimeField(default=django.utils.timezone.now)), ("is_active", models.BooleanField(default=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)),
            ("source", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="jobs", to="jobs_opportunity.jobsource")), ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="job_opportunities", to=settings.AUTH_USER_MODEL)),
        ], options={"ordering":["-published_at","-discovered_at"], "indexes":[models.Index(fields=["user","is_active"], name="jobs_job_user_active_idx"),models.Index(fields=["user","is_remote"], name="jobs_job_user_remote_idx"),models.Index(fields=["source","external_id"], name="jobs_job_source_ext_idx")], "constraints":[models.UniqueConstraint(fields=["user","source","external_id"], name="jobs_unique_external_per_user_source")]}),
        migrations.CreateModel(name="JobSkillRequirement", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("required_level", models.CharField(choices=[("beginner","Beginner"),("intermediate","Intermediate"),("advanced","Advanced"),("expert","Expert")], default="intermediate", max_length=20)), ("importance", models.PositiveSmallIntegerField(default=1)), ("job", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="skill_requirements", to="jobs_opportunity.jobopportunity")), ("skill", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="job_requirements", to="learning.skill")),
        ], options={"constraints":[models.UniqueConstraint(fields=["job","skill"], name="jobs_job_skill_unique")]}),
        migrations.CreateModel(name="JobMatch", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("score", models.PositiveSmallIntegerField(default=0)), ("matched_skills", models.JSONField(blank=True, default=list)), ("missing_skills", models.JSONField(blank=True, default=list)), ("reasons", models.JSONField(blank=True, default=list)), ("calculated_at", models.DateTimeField(auto_now=True)), ("job", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="matches", to="jobs_opportunity.jobopportunity")), ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="job_matches", to=settings.AUTH_USER_MODEL)),
        ], options={"ordering":["-score","-calculated_at"], "constraints":[models.UniqueConstraint(fields=["user","job"], name="jobs_user_job_match_unique")]}),
        migrations.CreateModel(name="JobApplication", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("status", models.CharField(choices=[("saved","Saved"),("applied","Applied"),("interview","Interview"),("offer","Offer"),("rejected","Rejected"),("withdrawn","Withdrawn")], default="saved", max_length=20)), ("notes", models.TextField(blank=True)), ("applied_at", models.DateTimeField(blank=True, null=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("job", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="applications", to="jobs_opportunity.jobopportunity")), ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="job_applications", to=settings.AUTH_USER_MODEL)),
        ], options={"constraints":[models.UniqueConstraint(fields=["user","job"], name="jobs_user_job_application_unique")]}),
    ]
