# Generated by Django 6.0.8 on 2026-09-26 19:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_opportunity', '0001_initial'),
        ('learning', '0002_alter_knowledgeapplication_knowledge_item'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='jobopportunity',
            new_name='jobs_opport_user_id_9dc439_idx',
            old_name='jobs_job_user_active_idx',
        ),
        migrations.RenameIndex(
            model_name='jobopportunity',
            new_name='jobs_opport_user_id_cf9629_idx',
            old_name='jobs_job_user_remote_idx',
        ),
        migrations.RenameIndex(
            model_name='jobopportunity',
            new_name='jobs_opport_source__eefe17_idx',
            old_name='jobs_job_source_ext_idx',
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='required_skills',
            field=models.ManyToManyField(related_name='job_opportunities', through='jobs_opportunity.JobSkillRequirement', to='learning.skill'),
        ),
        migrations.AlterField(
            model_name='jobmatch',
            name='score',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='jobskillrequirement',
            name='importance',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
