# Generated by Django 6.0.8 on 2026-09-27 22:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_opportunity', '0002_rename_jobs_job_user_active_idx_jobs_opport_user_id_9dc439_idx_and_more'),
        ('learning', '0003_learningnote_reflection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(default='job_match', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobAnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(default=django.utils.timezone.localdate)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplicationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='JobCoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Cover Letter', max_length=150)),
                ('content', models.TextField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(default='Interview', max_length=80)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('questions', models.JSONField(blank=True, default=list)),
                ('feedback', models.TextField(blank=True)),
                ('rating', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_titles', models.JSONField(blank=True, default=list)),
                ('locations', models.JSONField(blank=True, default=list)),
                ('preferred_job_types', models.JSONField(blank=True, default=list)),
                ('preferred_skills', models.JSONField(blank=True, default=list)),
                ('excluded_companies', models.JSONField(blank=True, default=list)),
                ('preferred_companies', models.JSONField(blank=True, default=list)),
                ('remote_preference', models.CharField(choices=[('any', 'Any'), ('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'On-site')], default='any', max_length=20)),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('score_weights', models.JSONField(blank=True, default=dict)),
                ('notification_settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobReadiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('level', models.CharField(default='not_ready', max_length=30)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('next_actions', models.JSONField(blank=True, default=list)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('is_seen', models.BooleanField(default=False)),
                ('is_saved', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-score', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='JobResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('file', models.FileField(blank=True, upload_to='jobs/resumes/%Y/%m/')),
                ('content', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='JobSavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('query', models.CharField(blank=True, max_length=255)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('alert_enabled', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobSkillGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('required_level', models.CharField(default='intermediate', max_length=20)),
                ('current_level', models.CharField(blank=True, max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('learning', 'Learning'), ('ready', 'Ready'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='expected_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='offer_currency',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='offer_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='jobmatch',
            name='breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='jobmatch',
            name='experience_score',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='jobmatch',
            name='goal_score',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='jobmatch',
            name='location_score',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='jobmatch',
            name='preference_score',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='jobmatch',
            name='salary_score',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='jobmatch',
            name='skill_score',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='ai_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='application_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='benefits',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='canonical_key',
            field=models.CharField(blank=True, db_index=True, max_length=400),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='experience_level',
            field=models.CharField(choices=[('entry', 'Entry'), ('junior', 'Junior'), ('mid', 'Mid'), ('senior', 'Senior'), ('lead', 'Lead'), ('executive', 'Executive'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='extracted_requirements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='freshness_score',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='location_type',
            field=models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'On-site'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='normalized_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='red_flags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='responsibilities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='salary_estimated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='salary_period',
            field=models.CharField(choices=[('hour', 'Hourly'), ('month', 'Monthly'), ('year', 'Yearly'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobskillrequirement',
            name='requirement_type',
            field=models.CharField(choices=[('required', 'Required'), ('preferred', 'Preferred'), ('optional', 'Optional')], default='required', max_length=20),
        ),
        migrations.AddField(
            model_name='jobsource',
            name='last_sync_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobsource',
            name='max_items_per_sync',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='jobsource',
            name='sync_interval_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('saved', 'Saved'), ('preparing', 'Preparing'), ('applied', 'Applied'), ('screening', 'Screening'), ('interview', 'Interview'), ('technical', 'Technical Interview'), ('final', 'Final Interview'), ('offer', 'Offer'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='saved', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobopportunity',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Full time'), ('part_time', 'Part time'), ('contract', 'Contract'), ('freelance', 'Freelance'), ('internship', 'Internship'), ('project', 'Project'), ('temporary', 'Temporary'), ('volunteer', 'Volunteer')], default='full_time', max_length=30),
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=150)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('size', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('is_followed', models.BooleanField(default=False)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='company_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobs_opportunity.companyprofile'),
        ),
        migrations.AddIndex(
            model_name='jobopportunity',
            index=models.Index(fields=['user', 'company'], name='jobs_opport_user_id_453303_idx'),
        ),
        migrations.AddIndex(
            model_name='jobopportunity',
            index=models.Index(fields=['user', 'location_type'], name='jobs_opport_user_id_486e65_idx'),
        ),
        migrations.AddIndex(
            model_name='jobopportunity',
            index=models.Index(fields=['user', 'experience_level'], name='jobs_opport_user_id_75cc66_idx'),
        ),
        migrations.AddIndex(
            model_name='jobopportunity',
            index=models.Index(fields=['user', 'published_at'], name='jobs_opport_user_id_c60473_idx'),
        ),
        migrations.AddField(
            model_name='jobalert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobanalyticssnapshot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_analytics_snapshots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobapplicationevent',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='jobs_opportunity.jobapplication'),
        ),
        migrations.AddField(
            model_name='jobcoverletter',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_letters', to='jobs_opportunity.jobopportunity'),
        ),
        migrations.AddField(
            model_name='jobcoverletter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_cover_letters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='jobs_opportunity.jobcoverletter'),
        ),
        migrations.AddField(
            model_name='jobinterview',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='jobs_opportunity.jobapplication'),
        ),
        migrations.AddField(
            model_name='jobpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_preference', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobreadiness',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_records', to='jobs_opportunity.jobopportunity'),
        ),
        migrations.AddField(
            model_name='jobreadiness',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_readiness', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobrecommendation',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='jobs_opportunity.jobopportunity'),
        ),
        migrations.AddField(
            model_name='jobrecommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobresume',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_resumes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobcoverletter',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_letters', to='jobs_opportunity.jobresume'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='jobs_opportunity.jobresume'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['user', 'status'], name='jobs_opport_user_id_6f8516_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['user', 'deadline'], name='jobs_opport_user_id_9c7612_idx'),
        ),
        migrations.AddField(
            model_name='jobsavedsearch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_saved_searches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobskillgap',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_gaps', to='jobs_opportunity.jobopportunity'),
        ),
        migrations.AddField(
            model_name='jobskillgap',
            name='learning_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_skill_gaps', to='learning.learninggoal'),
        ),
        migrations.AddField(
            model_name='jobskillgap',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_skill_gaps', to='learning.skill'),
        ),
        migrations.AddField(
            model_name='jobskillgap',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_skill_gaps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='companyprofile',
            constraint=models.UniqueConstraint(fields=('user', 'normalized_name'), name='jobs_company_user_normalized_unique'),
        ),
        migrations.AddIndex(
            model_name='jobalert',
            index=models.Index(fields=['user', 'is_read'], name='jobs_opport_user_id_c0043c_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobanalyticssnapshot',
            constraint=models.UniqueConstraint(fields=('user', 'snapshot_date'), name='jobs_user_snapshot_date_unique'),
        ),
        migrations.AddIndex(
            model_name='jobapplicationevent',
            index=models.Index(fields=['application', 'occurred_at'], name='jobs_opport_applica_32d93c_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobreadiness',
            constraint=models.UniqueConstraint(fields=('user', 'job'), name='jobs_user_job_readiness_unique'),
        ),
        migrations.AddConstraint(
            model_name='jobrecommendation',
            constraint=models.UniqueConstraint(fields=('user', 'job'), name='jobs_user_job_recommendation_unique'),
        ),
        migrations.AddIndex(
            model_name='jobskillgap',
            index=models.Index(fields=['user', 'status'], name='jobs_opport_user_id_cd8ed3_idx'),
        ),
        migrations.AddIndex(
            model_name='jobskillgap',
            index=models.Index(fields=['job', 'severity'], name='jobs_opport_job_id_445684_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobskillgap',
            constraint=models.UniqueConstraint(fields=('user', 'job', 'name'), name='jobs_user_job_gap_name_unique'),
        ),
    ]
