# Generated by Django 6.0.8 on 2026-09-26 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconversation',
            name='provider',
            field=models.CharField(choices=[('ollama', 'Ollama'), ('openai', 'OpenAI'), ('openrouter', 'OpenRouter')], default='ollama', max_length=50),
        ),
        migrations.CreateModel(
            name='AIPromptProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('system_prompt', models.TextField(blank=True)),
                ('context_instructions', models.TextField(blank=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('max_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_prompt_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AIProviderCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('ollama', 'Ollama'), ('openai', 'OpenAI'), ('openrouter', 'OpenRouter')], max_length=50)),
                ('encrypted_api_key', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_provider_credentials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_provider', models.CharField(choices=[('ollama', 'Ollama'), ('openai', 'OpenAI'), ('openrouter', 'OpenRouter')], default='ollama', max_length=50)),
                ('preferred_model', models.CharField(blank=True, default='', max_length=255)),
                ('context_enabled', models.BooleanField(default=True)),
                ('max_context_tokens', models.PositiveIntegerField(default=6000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_prompt_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_settings', to='ai.aipromptprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='aipromptprofile',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_user_ai_prompt_profile_name'),
        ),
        migrations.AddIndex(
            model_name='aiprovidercredential',
            index=models.Index(fields=['user', 'provider'], name='ai_aiprovid_user_id_12e443_idx'),
        ),
        migrations.AddConstraint(
            model_name='aiprovidercredential',
            constraint=models.UniqueConstraint(fields=('user', 'provider'), name='unique_user_ai_provider_credential'),
        ),
    ]
