<script setup>
import { ref, onMounted, onBeforeUnmount } from 'vue'
const open=ref(false), minimized=ref(false), logs=ref([]), status=ref('closed'), ws=ref(null), consoleEl=ref(null)
const enabled=true; const wsEnabled=import.meta.env.VITE_DEBUG_CONSOLE==='true'; const WS_URL=import.meta.env.VITE_DEBUG_WS_URL||'ws://127.0.0.1:8000/ws/debug/'
const addLog=(level,message)=>{logs.value=[...logs.value,{id:Date.now()+Math.random(),level,message,time:new Date().toLocaleTimeString('ar-EG',{hour12:false})}].slice(-500); requestAnimationFrame(()=>{if(consoleEl.value)consoleEl.value.scrollTop=consoleEl.value.scrollHeight})}
function connect(){if(!enabled||!wsEnabled||!open.value)return; if(ws.value)return; try{ws.value=new WebSocket(WS_URL);ws.value.onopen=()=>{status.value='connected';addLog('success','Debug Console connected')};ws.value.onmessage=e=>{try{const d=JSON.parse(e.data);addLog(d.level||'info',d.message||'')}catch{addLog('info',e.data)}};ws.value.onerror=()=>{status.value='error'};ws.value.onclose=()=>{status.value='closed';ws.value=null}}catch{status.value='error'}}
function disconnect(){ws.value?.close();ws.value=null;status.value='closed'}
function toggle(){open.value=!open.value;localStorage.setItem('debug_console_open',String(open.value)); if(open.value)connect();else disconnect()}
onMounted(()=>{open.value=localStorage.getItem('debug_console_open')==='true';if(open.value)connect()}); onBeforeUnmount(disconnect)
</script>
<template><div v-if="enabled" class="debug-wrap"><button class="debug-toggle" @click="toggle"><i class="pi pi-terminal"/> Debug</button><section v-if="open" class="console" :class="{minimized}"><header><strong>Live Debug Console</strong><span>{{status}}</span><div><button @click="logs=[]">Clear</button><button @click="minimized=!minimized">{{minimized?'▲':'▼'}}</button><button @click="toggle">×</button></div></header><div v-if="!minimized" ref="consoleEl" class="body"><div v-if="!logs.length">Waiting for Django logs...</div><div v-for="log in logs" :key="log.id" class="line"><span>{{log.time}}</span><b>{{log.level}}</b><span>{{log.message}}</span></div></div></section></div></template>
<style scoped>.debug-wrap{position:fixed;left:18px;bottom:18px;z-index:99999}.debug-toggle{background:#111827;color:#e5e7eb;border:1px solid #334155;border-radius:9px;padding:9px 12px;box-shadow:0 8px 30px #0005}.console{position:fixed;left:18px;right:18px;bottom:62px;height:300px;background:#07111f;border:1px solid #334155;border-radius:12px;color:#dbeafe;overflow:hidden;box-shadow:0 15px 50px #0008}.console.minimized{height:auto}.console header{display:flex;align-items:center;gap:12px;padding:10px 14px;border-bottom:1px solid #26364d}.console header span{color:#60a5fa;font-size:12px}.console header div{margin-left:auto;display:flex;gap:5px}.console button{background:#1f2937;color:#e5e7eb;border:0;border-radius:6px;padding:5px 8px}.body{height:calc(100% - 44px);overflow:auto;padding:10px;font:12px/1.6 monospace}.line{display:grid;grid-template-columns:85px 60px 1fr;gap:8px;border-bottom:1px solid #132238;padding:2px 0}.line span:first-child{color:#64748b}.line b{color:#93c5fd}@media(max-width:700px){.console{left:8px;right:8px}}
</style>