<script setup>
import { onMounted, ref } from 'vue'
import { getRecommendations, getSocialProfile, updateSocialProfile, sendFriendRequest } from '@/services/social'
const recommendations = ref([]); const profile = ref({ learning_interests: [], professional_interests: [], topics: [], looking_for: [], bio: '', discoverable: true }); const saving = ref(false)
const text = (v) => Array.isArray(v) ? v.join(', ') : v
const parse = (v) => v.split(',').map(x => x.trim()).filter(Boolean)
const load = async () => { const p = await getSocialProfile(); profile.value = {...p, learning_interests: text(p.learning_interests), professional_interests: text(p.professional_interests), topics: text(p.topics), looking_for: text(p.looking_for)}; recommendations.value = await getRecommendations() }
const save = async () => { saving.value = true; try { profile.value = await updateSocialProfile({...profile.value, learning_interests: parse(text(profile.value.learning_interests)), professional_interests: parse(text(profile.value.professional_interests)), topics: parse(text(profile.value.topics)), looking_for: parse(text(profile.value.looking_for))}); recommendations.value = await getRecommendations() } finally { saving.value = false } }
const connect = async (id) => { await sendFriendRequest(id); recommendations.value = recommendations.value.filter(x => x.candidate.id !== id) }
onMounted(load)
</script>
<template>
  <section class="space-y-6"><div><h1 class="text-2xl font-bold">Social</h1><p class="text-sm text-surface-500">Discover people through shared skills, learning and goals.</p></div>
    <div class="grid xl:grid-cols-[360px_1fr] gap-6"><div class="rounded-2xl border bg-white dark:bg-surface-900 p-5 space-y-4"><h2 class="font-semibold">What I'm looking for</h2><textarea v-model="profile.looking_for" class="w-full min-h-24 p-3 rounded-xl border bg-transparent" placeholder="Learning partner, Django mentor, Project partner" /><label class="block text-sm">Learning interests<textarea v-model="profile.learning_interests" class="w-full mt-1 p-3 rounded-xl border bg-transparent" /></label><label class="block text-sm">Professional interests<textarea v-model="profile.professional_interests" class="w-full mt-1 p-3 rounded-xl border bg-transparent" /></label><label class="block text-sm">Topics<textarea v-model="profile.topics" class="w-full mt-1 p-3 rounded-xl border bg-transparent" /></label><label class="flex gap-2 items-center text-sm"><input v-model="profile.discoverable" type="checkbox" /> Discoverable</label><button :disabled="saving" class="w-full py-2.5 rounded-xl bg-primary text-white" @click="save">{{ saving ? 'Saving…' : 'Save preferences' }}</button></div>
      <div><div v-if="!recommendations.length" class="p-10 rounded-2xl border border-dashed text-center text-surface-500">No strong matches yet. Add more interests and skills.</div><div v-else class="grid md:grid-cols-2 gap-4"><article v-for="rec in recommendations" :key="rec.id" class="rounded-2xl border bg-white dark:bg-surface-900 p-5"><div class="flex items-center gap-3"><div class="w-12 h-12 rounded-full bg-primary/10 text-primary grid place-items-center font-bold">{{ (rec.candidate.name || 'U')[0] }}</div><div><h2 class="font-semibold">{{ rec.candidate.name }} {{ rec.candidate.surname || '' }}</h2><div class="text-xs text-surface-500">Match {{ rec.score }}%</div></div></div><ul class="mt-4 space-y-2 text-sm"><li v-for="reason in rec.reasons" :key="reason">• {{ reason }}</li></ul><button class="mt-4 px-4 py-2 rounded-lg bg-primary text-white" @click="connect(rec.candidate.id)">Connect</button></article></div></div></div>
  </section>
</template>
