<template><div class="page"><header><div><span>AI CONTROL CENTER</span><h1>AI</h1><p>كل طلب يمر من Django إلى Provider، والعمليات الطويلة يمكن تشغيلها عبر Celery.</p></div><Tag :value="settings.preferred_provider" severity="info"/></header><div class="grid"><Card><template #title>Chat</template><template #content><div class="messages"><div v-for="m in messages" :key="m.id" :class="['message',m.role]"><small>{{m.role}}</small><div>{{m.content}}</div></div></div><div class="composer"><Textarea v-model="prompt" rows="4" placeholder="اكتب طلبك..."/><Button label="Send" icon="pi pi-send" :loading="sending" @click="send"/></div></template></Card><Card><template #title>Learning Plan Generator</template><template #content><Textarea v-model="planPrompt" rows="6" placeholder="مثال: أريد تعلم Django Advanced خلال 8 أسابيع"/><div class="buttons"><Button label="Preview" icon="pi pi-sparkles" :loading="generating" @click="generate"/><Button v-if="plan" label="Approve & Create" severity="success" @click="approve"/></div><Message v-if="taskStatus" severity="info">Task: {{taskStatus.status}}</Message><pre v-if="plan">{{JSON.stringify(plan,null,2)}}</pre></template></Card></div></div></template>
<script setup>
import { onMounted, ref } from 'vue'; import Button from 'primevue/button'; import Card from 'primevue/card'; import Textarea from 'primevue/textarea'; import Tag from 'primevue/tag'; import Message from 'primevue/message'; import { sendMessage } from '@/services/ai'; import { getAISettings,previewLearningPlan,approveLearningPlan,startLearningPlanAsync,getTaskStatus } from '@/services/aiControl'
const settings=ref({preferred_provider:'ollama',preferred_model:''}),messages=ref([]),prompt=ref(''),planPrompt=ref(''),plan=ref(null),sending=ref(false),generating=ref(false),taskStatus=ref(null)
async function load(){try{settings.value=await getAISettings()}catch{}}
async function send(){if(!prompt.value.trim())return;sending.value=true;try{const r=await sendMessage({message:prompt.value,provider:settings.value.preferred_provider,model:settings.value.preferred_model});messages.value.push({id:Date.now(),role:'user',content:prompt.value},{id:Date.now()+1,role:'assistant',content:r.message?.content||r.error||'No response'});prompt.value=''}finally{sending.value=false}}
async function generate(){if(!planPrompt.value.trim())return;generating.value=true;try{const r=await previewLearningPlan({message:planPrompt.value,provider:settings.value.preferred_provider,model:settings.value.preferred_model});plan.value=r.plan}catch(e){const r=await startLearningPlanAsync({message:planPrompt.value,provider:settings.value.preferred_provider,model:settings.value.preferred_model});taskStatus.value=r;poll(r.task_id)}finally{generating.value=false}}
async function poll(id){for(let i=0;i<30;i++){await new Promise(r=>setTimeout(r,2000));taskStatus.value=await getTaskStatus(id);if(['completed','success','failed'].includes(taskStatus.value.status)){if(taskStatus.value.result)plan.value=taskStatus.value.result;break}}}
async function approve(){if(plan.value)await approveLearningPlan(plan.value)}
onMounted(load)
</script>
<style scoped>.page{max-width:1300px;margin:auto;padding:32px}.page header{display:flex;justify-content:space-between;margin-bottom:24px}.page header span{font-size:12px;color:#a78bfa;letter-spacing:.15em}.page h1{font-size:34px;margin:5px 0}.page header p{color:#94a3b8}.grid{display:grid;grid-template-columns:1.3fr 1fr;gap:18px}.messages{height:420px;overflow:auto;display:grid;align-content:start;gap:12px}.message{max-width:80%;padding:12px;border-radius:14px;background:var(--p-surface-100)}.message.user{justify-self:end;background:var(--p-primary-color);color:#fff}.message small{display:block;opacity:.65;margin-bottom:4px}.composer{display:grid;gap:10px;margin-top:12px}.buttons{display:flex;gap:10px;margin-top:12px}pre{white-space:pre-wrap;max-height:420px;overflow:auto;background:#020617;padding:12px;border-radius:10px;margin-top:16px}@media(max-width:800px){.page{padding:18px}.grid{grid-template-columns:1fr}}
</style>
