# Generated by Django 6.0.8 on 2026-10-01 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_88c319_idx',
            old_name='notification_user_read_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_b00d31_idx',
            old_name='notification_user_type_idx',
        ),
    ]
