from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial=True
    dependencies=[migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
        migrations.CreateModel(name="ProjectRegistry",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("key",models.CharField(default="so_iam_os",max_length=120,unique=True)),("name",models.CharField(default="SO_IAM_OS",max_length=200)),("root_path",models.CharField(blank=True,max_length=500)),("metadata",models.JSONField(blank=True,default=dict)),("scanned_at",models.DateTimeField(blank=True,null=True)),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True))]),
        migrations.CreateModel(name="Feature",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("key",models.CharField(max_length=180)),("name",models.CharField(max_length=220)),("app_label",models.CharField(blank=True,max_length=100)),("description",models.TextField(blank=True)),("status",models.CharField(choices=[("active","Active"),("planned","Planned"),("deprecated","Deprecated")],default="active",max_length=20)),("protected",models.BooleanField(default=False)),("metadata",models.JSONField(blank=True,default=dict)),("project",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="features",to="codex.projectregistry"))],options={"constraints":[models.UniqueConstraint(fields=["project","key"],name="codex_feature_project_key")]}),
        migrations.CreateModel(name="FileRegistry",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("path",models.CharField(max_length=700)),("kind",models.CharField(blank=True,max_length=80)),("app_label",models.CharField(blank=True,max_length=100)),("sha256",models.CharField(blank=True,max_length=64)),("size",models.PositiveBigIntegerField(default=0)),("protected",models.BooleanField(default=False)),("metadata",models.JSONField(blank=True,default=dict)),("scanned_at",models.DateTimeField(auto_now=True)),("project",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="files",to="codex.projectregistry"))],options={"constraints":[models.UniqueConstraint(fields=["project","path"],name="codex_file_project_path")]}),
        migrations.CreateModel(name="APIEndpoint",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("method",models.CharField(default="ANY",max_length=16)),("path",models.CharField(max_length=700)),("name",models.CharField(blank=True,max_length=240)),("source",models.CharField(blank=True,max_length=300)),("app_label",models.CharField(blank=True,max_length=100)),("frontend_route",models.CharField(default="/codex",max_length=220)),("frontend_section",models.CharField(default="API Registry",max_length=160)),("frontend_service",models.CharField(blank=True,max_length=220)),("coverage_status",models.CharField(default="registry-covered",max_length=40)),("protected",models.BooleanField(default=False)),("metadata",models.JSONField(blank=True,default=dict)),("project",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="apis",to="codex.projectregistry"))],options={"constraints":[models.UniqueConstraint(fields=["project","method","path","name"],name="codex_api_unique")]}),
        migrations.CreateModel(name="ProtectedFeature",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("key",models.CharField(max_length=180)),("reason",models.TextField(blank=True)),("paths",models.JSONField(blank=True,default=list)),("rules",models.JSONField(blank=True,default=dict)),("enabled",models.BooleanField(default=True)),("created_at",models.DateTimeField(auto_now_add=True)),("feature",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.CASCADE,related_name="protection_rules",to="codex.feature")),("project",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="protected_features",to="codex.projectregistry"))],options={"constraints":[models.UniqueConstraint(fields=["project","key"],name="codex_protected_project_key")]}),
        migrations.CreateModel(name="ChangeSet",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("title",models.CharField(max_length=240)),("objective",models.TextField(blank=True)),("status",models.CharField(choices=[("planned","Planned"),("approved","Approved"),("applied","Applied"),("rolled_back","Rolled back"),("rejected","Rejected")],default="planned",max_length=30)),("impact",models.JSONField(blank=True,default=dict)),("plan",models.JSONField(blank=True,default=list)),("diff_summary",models.JSONField(blank=True,default=dict)),("snapshot_id",models.CharField(blank=True,max_length=120)),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("created_by",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL)),("project",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="changesets",to="codex.projectregistry"))]),
        migrations.CreateModel(name="ProjectSnapshot",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("label",models.CharField(max_length=220)),("manifest",models.JSONField(blank=True,default=dict)),("created_at",models.DateTimeField(auto_now_add=True)),("created_by",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL)),("project",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="snapshots",to="codex.projectregistry"))]),
    ]
