from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies = [('codex', '0002_codexconversation_codexanalysis_codexmessage')]
    operations = [
        migrations.CreateModel(name='ArchitectureNode', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('key', models.CharField(max_length=500)), ('kind', models.CharField(max_length=80)), ('label', models.CharField(max_length=300)), ('path', models.CharField(blank=True, max_length=700)), ('metadata', models.JSONField(blank=True, default=dict)), ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='architecture_nodes', to='codex.projectregistry'))], options={'constraints':[models.UniqueConstraint(fields=['project','key'], name='codex_arch_node_unique')]}),
        migrations.CreateModel(name='CodexPolicy', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('permissions', models.JSONField(blank=True, default=dict)), ('updated_at', models.DateTimeField(auto_now=True)), ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='codex.projectregistry')), ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL))], options={'constraints':[models.UniqueConstraint(fields=['project','user'], name='codex_policy_project_user_unique')]}),
        migrations.CreateModel(name='CodexTool', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('key', models.CharField(max_length=160)), ('name', models.CharField(max_length=220)), ('capability', models.CharField(default='read', max_length=60)), ('enabled', models.BooleanField(default=True)), ('metadata', models.JSONField(blank=True, default=dict)), ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='codex.projectregistry'))], options={'constraints':[models.UniqueConstraint(fields=['project','key'], name='codex_tool_project_key_unique')]}),
        migrations.CreateModel(name='CodexAuditEvent', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('event_type', models.CharField(max_length=100)), ('action', models.CharField(max_length=180)), ('status', models.CharField(default='success', max_length=40)), ('payload', models.JSONField(blank=True, default=dict)), ('created_at', models.DateTimeField(auto_now_add=True)), ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='codex.projectregistry')), ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='CodexFinding', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('category', models.CharField(max_length=80)), ('severity', models.CharField(default='medium', max_length=30)), ('title', models.CharField(max_length=220)), ('path', models.CharField(blank=True, max_length=700)), ('line', models.PositiveIntegerField(blank=True, null=True)), ('message', models.TextField()), ('metadata', models.JSONField(blank=True, default=dict)), ('resolved', models.BooleanField(default=False)), ('created_at', models.DateTimeField(auto_now_add=True)), ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='codex.projectregistry'))]),
        migrations.CreateModel(name='CodexAgentRun', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('request', models.TextField()), ('mode', models.CharField(default='safe-agent', max_length=60)), ('status', models.CharField(choices=[('planned','Planned'),('approved','Approved'),('running','Running'),('completed','Completed'),('failed','Failed'),('cancelled','Cancelled')], default='planned', max_length=30)), ('plan', models.JSONField(blank=True, default=dict)), ('result', models.JSONField(blank=True, default=dict)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='codex.projectregistry')), ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.SET_NULL, to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='CodexExecutionRequest', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('tool_key', models.CharField(max_length=160)), ('status', models.CharField(choices=[('pending','Pending'),('approved','Approved'),('running','Running'),('completed','Completed'),('failed','Failed'),('denied','Denied')], default='pending', max_length=30)), ('approval_note', models.TextField(blank=True)), ('result', models.JSONField(blank=True, default=dict)), ('created_at', models.DateTimeField(auto_now_add=True)), ('completed_at', models.DateTimeField(blank=True, null=True)), ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_requests', to='codex.projectregistry')), ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.SET_NULL, to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='ArchitectureEdge', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('relation', models.CharField(max_length=120)), ('metadata', models.JSONField(blank=True, default=dict)), ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='architecture_edges', to='codex.projectregistry')), ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_edges', to='codex.architecturenode')), ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_edges', to='codex.architecturenode'))], options={'constraints':[models.UniqueConstraint(fields=['project','source','target','relation'], name='codex_arch_edge_unique')]}),
        migrations.CreateModel(name='CodexChangeFile', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('path', models.CharField(max_length=700)), ('before_content', models.TextField(blank=True)), ('after_content', models.TextField(blank=True)), ('before_sha256', models.CharField(blank=True, max_length=64)), ('after_sha256', models.CharField(blank=True, max_length=64)), ('created_at', models.DateTimeField(auto_now_add=True)), ('changeset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_changes', to='codex.changeset'))]),
    ]
