<template><div><h5 id="📚-install-setup-vue-libraries" tabindex="-1"><a class="header-anchor" href="#📚-install-setup-vue-libraries"><span>📚 Install &amp; Setup Vue Libraries</span></a></h5>
<h3 id="_5️⃣-font-awesome" tabindex="-1"><a class="header-anchor" href="#_5️⃣-font-awesome"><span>5️⃣ Font Awesome</span></a></h3>
<h3 id="_1️⃣-install-📚" tabindex="-1"><a class="header-anchor" href="#_1️⃣-install-📚"><span>1️⃣ Install 📚</span></a></h3>
<div class="language-cmd line-numbers-mode" data-highlighter="prismjs" data-ext="cmd"><pre v-pre><code><span class="line">npm i --save @fortawesome/fontawesome-svg-core @fortawesome/vue-fontawesome@latest @fortawesome/vue-fontawesome@prerelease @fortawesome/free-solid-svg-icons @fortawesome/free-brands-svg-icons @fortawesome/free-regular-svg-icons</span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h3 id="_2️⃣-setup-🛠️" tabindex="-1"><a class="header-anchor" href="#_2️⃣-setup-🛠️"><span>2️⃣ Setup 🛠️</span></a></h3>
<h4 id="import-inside-main-js" tabindex="-1"><a class="header-anchor" href="#import-inside-main-js"><span>Import Inside main.js</span></a></h4>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre v-pre><code><span class="line"><span class="token comment">// Font Awesome</span></span>
<span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> FontAwesomeIcon <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">"@fortawesome/vue-fontawesome"</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> library <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">"@fortawesome/fontawesome-svg-core"</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> fas <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">"@fortawesome/free-solid-svg-icons"</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> fab <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">"@fortawesome/free-brands-svg-icons"</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> far <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">"@fortawesome/free-regular-svg-icons"</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// Add Free Icons Styles To SVG Core</span></span>
<span class="line">library<span class="token punctuation">.</span><span class="token function">add</span><span class="token punctuation">(</span>fas<span class="token punctuation">,</span> far<span class="token punctuation">,</span> fab<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre v-pre><code><span class="line"><span class="token comment">// eslint-disable-next-line vue/multi-word-component-names</span></span>
<span class="line">app<span class="token punctuation">.</span><span class="token function">component</span><span class="token punctuation">(</span><span class="token string">"fa"</span><span class="token punctuation">,</span> FontAwesomeIcon<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


