# Generated by Django 6.0.8 on 2026-09-17 01:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('assessment_type', models.CharField(choices=[('quiz', 'Quiz'), ('quick_check', 'Quick Check'), ('practical', 'Practical'), ('project', 'Project')], default='quiz', max_length=20)),
                ('passing_score', models.PositiveSmallIntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('estimated_minutes', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('passed', models.BooleanField(default=False)),
                ('feedback', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learning.assessment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('single_choice', 'Single choice'), ('multiple_select', 'Multiple select'), ('true_false', 'True / False'), ('short_answer', 'Short answer'), ('practical', 'Practical task')], max_length=30)),
                ('prompt', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('points', models.PositiveIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('grading_data', models.JSONField(blank=True, default=dict)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.assessment')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_correct', models.BooleanField(default=False)),
                ('feedback', models.TextField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='learning.assessmentquestion')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('points_awarded', models.FloatField(default=0)),
                ('feedback', models.TextField(blank=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='learning.assessmentattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='learning.assessmentquestion')),
                ('selected_choices', models.ManyToManyField(blank=True, related_name='responses', to='learning.assessmentchoice')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('application_type', models.CharField(choices=[('code', 'Code'), ('project', 'Project'), ('explanation', 'Explanation'), ('workflow', 'Workflow'), ('experiment', 'Experiment'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('knowledge_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='knowledge.knowledgeitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='learning.knowledgeapplication')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mastery_level', models.CharField(choices=[('beginner', 'Beginner'), ('developing', 'Developing'), ('competent', 'Competent'), ('advanced', 'Advanced'), ('mastered', 'Mastered')], default='developing', max_length=20)),
                ('understood', models.JSONField(blank=True, default=list)),
                ('applied', models.JSONField(blank=True, default=list)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('needs_review', models.JSONField(blank=True, default=list)),
                ('knowledge_gaps', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('feedback', models.TextField(blank=True)),
                ('ai_metadata', models.JSONField(blank=True, default=dict)),
                ('reviewed_by', models.CharField(default='ai', max_length=100)),
                ('reviewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='learning.applicationsubmission')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='learning.knowledgeapplication')),
            ],
            options={
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('current_level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=20)),
                ('target_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused'), ('archived', 'Archived')], default='active', max_length=20)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused'), ('archived', 'Archived')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths', to='learning.learninggoal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('difficulty', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('estimated_minutes', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('knowledge_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_topics', to='knowledge.knowledgeitem')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='learning.learningpath')),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='unlocked_topics', to='learning.learningtopic')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepts', models.JSONField(blank=True, default=list)),
                ('recommendation', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='planned', max_length=20)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_sessions', to='learning.applicationreview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_revisions', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='learning.learningtopic')),
            ],
            options={
                'ordering': ['scheduled_for', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percent', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('practice_completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('mastery_level', models.CharField(choices=[('not_started', 'Not Started'), ('beginner', 'Beginner'), ('developing', 'Developing'), ('competent', 'Competent'), ('advanced', 'Advanced'), ('mastered', 'Mastered')], default='not_started', max_length=20)),
                ('last_ai_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('needs_review', models.BooleanField(default=False)),
                ('lesson_completed', models.BooleanField(default=False)),
                ('quick_check_completed', models.BooleanField(default=False)),
                ('assessment_completed', models.BooleanField(default=False)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='learning.learningtopic')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='knowledgeapplication',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='learning.learningtopic'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='learning.learningtopic'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('content_format', models.CharField(choices=[('text', 'Plain text'), ('markdown', 'Markdown'), ('structured', 'Structured JSON')], default='markdown', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('estimated_minutes', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('learning_objectives', models.JSONField(blank=True, default=list)),
                ('key_concepts', models.JSONField(blank=True, default=list)),
                ('examples', models.JSONField(blank=True, default=list)),
                ('practical_instructions', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='learning.learningtopic')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('lesson', 'Lesson'), ('practice', 'Practice'), ('assessment', 'Assessment'), ('review', 'Review'), ('reading', 'Reading'), ('other', 'Other')], default='lesson', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('completed', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_sessions', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='learning.learningtopic')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='learning.lesson')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('reference_type', models.CharField(choices=[('website', 'Website'), ('documentation', 'Documentation'), ('article', 'Article'), ('book', 'Book'), ('video', 'Video'), ('file', 'File'), ('image', 'Image'), ('note', 'Personal note'), ('code', 'Code example'), ('other', 'Other')], default='website', max_length=30)),
                ('url', models.URLField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='learning/resources/%Y/%m/')),
                ('content', models.TextField(blank=True)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='learning.learningtopic')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='learning.lesson')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('general', 'General'), ('summary', 'Summary'), ('question', 'Question'), ('insight', 'Insight'), ('example', 'Example'), ('confusion', 'Confusion'), ('revision', 'Revision')], default='general', max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('knowledge_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_notes', to='knowledge.knowledgeitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_notes', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='learning.learningtopic')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='learning.lesson')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='knowledgeapplication',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='learning.lesson'),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='learning_sk_categor_788bee_idx')],
            },
        ),
        migrations.AddField(
            model_name='learningtopic',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_topics', to='learning.skill'),
        ),
        migrations.AddField(
            model_name='learninggoal',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_goals', to='learning.skill'),
        ),
        migrations.AddIndex(
            model_name='assessmentattempt',
            index=models.Index(fields=['user', 'assessment', 'started_at'], name='learning_as_user_id_528553_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentattempt',
            constraint=models.UniqueConstraint(fields=('assessment', 'user', 'attempt_number'), name='unique_assessment_attempt_number'),
        ),
        migrations.AddIndex(
            model_name='assessmentquestion',
            index=models.Index(fields=['assessment', 'order'], name='learning_as_assessm_cae64f_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentresponse',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_response_per_attempt_question'),
        ),
        migrations.AddConstraint(
            model_name='applicationsubmission',
            constraint=models.UniqueConstraint(fields=('application', 'version'), name='unique_application_submission_version'),
        ),
        migrations.AddIndex(
            model_name='applicationreview',
            index=models.Index(fields=['application', 'reviewed_at'], name='learning_ap_applica_14666d_idx'),
        ),
        migrations.AddIndex(
            model_name='learningpath',
            index=models.Index(fields=['user', 'status'], name='learning_le_user_id_517efd_idx'),
        ),
        migrations.AddIndex(
            model_name='learningpath',
            index=models.Index(fields=['goal', 'status'], name='learning_le_goal_id_7ad53a_idx'),
        ),
        migrations.AddIndex(
            model_name='learningrevision',
            index=models.Index(fields=['user', 'status', 'scheduled_for'], name='learning_le_user_id_2930fb_idx'),
        ),
        migrations.AddIndex(
            model_name='learningprogress',
            index=models.Index(fields=['user', 'needs_review'], name='learning_le_user_id_981021_idx'),
        ),
        migrations.AddIndex(
            model_name='learningprogress',
            index=models.Index(fields=['user', 'last_activity_at'], name='learning_le_user_id_62fd38_idx'),
        ),
        migrations.AddConstraint(
            model_name='learningprogress',
            constraint=models.UniqueConstraint(fields=('topic', 'user'), name='unique_learning_progress_per_user_topic'),
        ),
        migrations.AddConstraint(
            model_name='learningprogress',
            constraint=models.CheckConstraint(condition=models.Q(('progress_percent__gte', 0), ('progress_percent__lte', 100)), name='learning_progress_percent_0_100'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['topic', 'assessment_type', 'is_active'], name='learning_as_topic_i_88c302_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.CheckConstraint(condition=models.Q(('passing_score__gte', 0), ('passing_score__lte', 100)), name='assessment_passing_score_0_100'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['topic', 'order'], name='learning_le_topic_i_cd31e1_idx'),
        ),
        migrations.AddIndex(
            model_name='learningsession',
            index=models.Index(fields=['user', 'started_at'], name='learning_le_user_id_0e7fdb_idx'),
        ),
        migrations.AddIndex(
            model_name='learningsession',
            index=models.Index(fields=['topic', 'started_at'], name='learning_le_topic_i_24facc_idx'),
        ),
        migrations.AddIndex(
            model_name='learningresource',
            index=models.Index(fields=['topic', 'order'], name='learning_le_topic_i_016bd0_idx'),
        ),
        migrations.AddIndex(
            model_name='learningnote',
            index=models.Index(fields=['user', 'topic'], name='learning_le_user_id_dc0ca7_idx'),
        ),
        migrations.AddIndex(
            model_name='learningnote',
            index=models.Index(fields=['user', 'note_type'], name='learning_le_user_id_408a4f_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeapplication',
            index=models.Index(fields=['user', 'topic', 'status'], name='learning_kn_user_id_1033ea_idx'),
        ),
        migrations.AddIndex(
            model_name='learningtopic',
            index=models.Index(fields=['path', 'order'], name='learning_le_path_id_8ea2a4_idx'),
        ),
        migrations.AddIndex(
            model_name='learningtopic',
            index=models.Index(fields=['path', 'status'], name='learning_le_path_id_746e08_idx'),
        ),
        migrations.AddConstraint(
            model_name='learningtopic',
            constraint=models.UniqueConstraint(fields=('path', 'order'), name='learning_topic_unique_path_order'),
        ),
        migrations.AddIndex(
            model_name='learninggoal',
            index=models.Index(fields=['user', 'status'], name='learning_le_user_id_647c98_idx'),
        ),
        migrations.AddIndex(
            model_name='learninggoal',
            index=models.Index(fields=['user', 'target_date'], name='learning_le_user_id_ded592_idx'),
        ),
    ]
