# Generated by Django 6.0.8 on 2026-09-16 02:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_knowledgeitem_learning_topic'),
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mastery_level', models.CharField(default='developing', max_length=30)),
                ('understood', models.JSONField(blank=True, default=list)),
                ('applied', models.JSONField(blank=True, default=list)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('needs_review', models.JSONField(blank=True, default=list)),
                ('feedback', models.TextField(blank=True)),
                ('ai_metadata', models.JSONField(blank=True, default=dict)),
                ('reviewed_by', models.CharField(default='ai', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='learningprogress',
            name='last_ai_score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='learningprogress',
            name='mastery_level',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('beginner', 'Beginner'), ('developing', 'Developing'), ('competent', 'Competent'), ('advanced', 'Advanced'), ('mastered', 'Mastered')], default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='learningprogress',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='learningprogress',
            constraint=models.UniqueConstraint(fields=('topic', 'user'), name='unique_learning_progress_per_user_topic'),
        ),
        migrations.AddField(
            model_name='knowledgeapplication',
            name='knowledge_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='knowledge.knowledgeitem'),
        ),
        migrations.AddField(
            model_name='knowledgeapplication',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='learning.learningtopic'),
        ),
        migrations.AddField(
            model_name='knowledgeapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationreview',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='learning.knowledgeapplication'),
        ),
    ]
