# Generated by Django 6.0.8 on 2026-09-26 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_rename_knowledge_k_knowled_c6a337_idx_knowledge_file_type_idx_and_more'),
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgeapplication',
            name='knowledge_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_applications', to='knowledge.knowledgeitem'),
        ),
    ]
