# Generated by Django 6.0.8 on 2026-10-02 17:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('seconds', models.IntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('executable_path', models.CharField(max_length=500)),
                ('project_path', models.CharField(blank=True, max_length=500, null=True)),
                ('working_directory', models.CharField(blank=True, max_length=500, null=True)),
                ('window_title_pattern', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='programs')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramElement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('display_text', models.CharField(blank=True, max_length=500)),
                ('element_type', models.CharField(choices=[('BUTTON', 'Button'), ('INPUT', 'Text Input'), ('CHECKBOX', 'Checkbox'), ('RADIO', 'Radio Button'), ('MENU', 'Menu Item'), ('LISTBOX', 'List Box'), ('COMBOBOX', 'Combo Box'), ('TAB', 'Tab Control'), ('LINK', 'Hyperlink'), ('TEXT', 'Static Text'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('automation_id', models.CharField(blank=True, db_index=True, max_length=500)),
                ('class_name', models.CharField(blank=True, default='default_value', max_length=500)),
                ('selector_type', models.CharField(choices=[('ui', 'UI Automation'), ('image', 'Image Recognition'), ('coords', 'Screen Coordinates'), ('text', 'Text OCR')], default='ui', max_length=20)),
                ('selector_value', models.TextField(blank=True)),
                ('keyboard_shortcut', models.CharField(blank=True, default='', max_length=100)),
                ('help_text', models.TextField(blank=True)),
                ('x_coordinate', models.IntegerField(blank=True, null=True)),
                ('y_coordinate', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('tree_path', models.CharField(blank=True, max_length=1000)),
                ('depth_level', models.IntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_clickable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('raw_properties', models.JSONField(default=dict)),
                ('stability_score', models.FloatField(default=1.0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='programs_element')),
                ('confidence', models.FloatField(default=0.8)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='automation.programelement')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='automation.program')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='automation.program')),
            ],
        ),
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('logs', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScreenState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('screenshot', models.ImageField(upload_to='screens')),
                ('detected_elements', models.JSONField(default=dict)),
                ('active_program', models.CharField(max_length=100)),
                ('action_id', models.UUIDField()),
                ('screenshot_path', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_states', to='automation.taskrun')),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused')], default='draft', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='taskrun',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.workflow'),
        ),
        migrations.CreateModel(
            name='WorkflowNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node_type', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('position_x', models.FloatField()),
                ('position_y', models.FloatField()),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automation.programelement')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automation.program')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='automation.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condition', models.CharField(blank=True, default='success', max_length=100, null=True)),
                ('edge_type', models.CharField(default='default', max_length=50)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='automation.workflow')),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_edges', to='automation.workflownode')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_edges', to='automation.workflownode')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='automation.workflownode')),
            ],
        ),
        migrations.AddIndex(
            model_name='programelement',
            index=models.Index(fields=['program', 'automation_id'], name='automation__program_32ff37_idx'),
        ),
        migrations.AddIndex(
            model_name='programelement',
            index=models.Index(fields=['program', 'name'], name='automation__program_61c576_idx'),
        ),
    ]
