# Generated by Django 6.0.8 on 2026-10-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userlearningsettings_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlearningsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
