<template><div class="jobs-page"><header class="head"><div><span class="eyebrow">CAREER</span><h1>Job Opportunities</h1><p>وظائف وفرص حقيقية مرتبطة بمهاراتك وLearning Progress.</p></div><div class="actions"><Button label="Refresh Matches" icon="pi pi-sync" :loading="refreshing" @click="refresh"/><Button label="إضافة فرصة" icon="pi pi-plus" @click="openCreate"/></div></header><Message v-if="error" severity="error">{{ error }}</Message><Card><template #content><div class="filters"><InputText v-model="q" placeholder="ابحث عن وظيفة أو شركة..." @keyup.enter="load"/><Select v-model="remote" :options="remoteOptions" optionLabel="label" optionValue="value" placeholder="Remote"/><Button icon="pi pi-search" label="بحث" @click="load"/></div><DataTable :value="jobs" :loading="loading" paginator :rows="8" stripedRows><Column field="title" header="Opportunity"><template #body="s"><strong>{{s.data.title}}</strong><small>{{s.data.company}}</small></template></Column><Column field="location" header="Location"/><Column header="Match"><template #body="s"><Tag :value="s.data.match ? `${s.data.match.score}%` : '—'" severity="success"/></template></Column><Column header="Skills"><template #body="s"><span>{{s.data.skill_requirements?.length||0}} required</span></template></Column><Column header="Actions"><template #body="s"><div class="row-actions"><Button icon="pi pi-refresh" text rounded @click="match(s.data)"/><Button icon="pi pi-check" text rounded @click="apply(s.data)"/><a v-if="s.data.url" :href="s.data.url" target="_blank" rel="noopener">Open</a></div></template></Column></DataTable></template></Card><Dialog v-model:visible="dialog" modal header="إضافة Job" :style="{width:'620px'}"><div class="form"><InputText v-model="form.title" placeholder="Title"/><InputText v-model="form.company" placeholder="Company"/><InputText v-model="form.url" placeholder="https://..."/><InputText v-model="form.location" placeholder="Location"/><Textarea v-model="form.description" rows="6" placeholder="Description"/><Select v-model="form.job_type" :options="jobTypes" optionLabel="label" optionValue="value"/><div class="check"><input type="checkbox" v-model="form.is_remote"/> Remote</div></div><template #footer><Button label="إلغاء" text @click="dialog=false"/><Button label="حفظ" :loading="saving" @click="save"/></template></Dialog></div></template>
<script setup>
import { onMounted, reactive, ref } from 'vue'
import Button from 'primevue/button'; import Card from 'primevue/card'; import DataTable from 'primevue/datatable'; import Column from 'primevue/column'; import InputText from 'primevue/inputtext'; import Select from 'primevue/select'; import Textarea from 'primevue/textarea'; import Dialog from 'primevue/dialog'; import Tag from 'primevue/tag'; import Message from 'primevue/message'
import { listJobs, createJob, refreshJobMatch, refreshMatches, applyToJob } from '@/services/jobs'
const jobs=ref([]),loading=ref(false),refreshing=ref(false),saving=ref(false),error=ref(''),q=ref(''),remote=ref(null),dialog=ref(false)
const remoteOptions=[{label:'All',value:null},{label:'Remote only',value:'true'}], jobTypes=[{label:'Full time',value:'full_time'},{label:'Contract',value:'contract'},{label:'Freelance',value:'freelance'},{label:'Project',value:'project'}]
const form=reactive({title:'',company:'',url:'',location:'',description:'',job_type:'full_time',is_remote:false})
async function load(){loading.value=true;try{jobs.value=await listJobs({q:q.value,remote:remote.value||undefined})}catch(e){error.value=e.response?.data?.detail||'تعذر تحميل الوظائف.'}finally{loading.value=false}}
async function refresh(){refreshing.value=true;try{await refreshMatches();await load()}catch(e){error.value='تعذر تحديث الـ Match.'}finally{refreshing.value=false}}
async function match(job){try{await refreshJobMatch(job.id);await load()}catch(e){error.value='تعذر حساب الـ Match.'}}
async function apply(job){try{await applyToJob(job.id,{status:'applied'});await load()}catch(e){error.value='تعذر تسجيل التقديم.'}}
function openCreate(){Object.assign(form,{title:'',company:'',url:'',location:'',description:'',job_type:'full_time',is_remote:false});dialog.value=true}
async function save(){saving.value=true;try{await createJob(form);dialog.value=false;await load()}catch(e){error.value='تعذر إنشاء الوظيفة.'}finally{saving.value=false}}
onMounted(load)
</script>
<style scoped>.jobs-page{max-width:1440px;margin:auto;padding:32px}.head{display:flex;justify-content:space-between;gap:20px;margin-bottom:24px}.eyebrow{color:#60a5fa;font-size:12px;letter-spacing:.15em}.head h1{margin:6px 0;font-size:34px}.head p{color:#94a3b8}.actions,.filters,.row-actions{display:flex;gap:10px;align-items:center}.filters{margin-bottom:18px}.filters .p-inputtext{flex:1}.form{display:grid;gap:12px}.form .p-inputtext,.form .p-select,.form .p-textarea{width:100%}.check{display:flex;gap:8px;align-items:center}small{display:block;color:#94a3b8}a{color:#60a5fa}@media(max-width:700px){.jobs-page{padding:18px}.head{flex-direction:column}.filters{flex-direction:column;align-items:stretch}}</style>
